# Generated by Django 4.1.3 on 2022-12-04 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('paterno', models.CharField(blank=True, max_length=50, null=True)),
                ('materno', models.CharField(blank=True, max_length=50, null=True)),
                ('numero', models.CharField(blank=True, max_length=5, null=True)),
                ('activo', models.BooleanField(blank=True, default=True, null=True)),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rol.rol')),
            ],
            options={
                'db_table': 'empleados',
                'managed': True,
            },
        ),
    ]
