# Generated by Django 4.1.3 on 2022-12-05 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compensaciones', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compensaciones',
        ),
    ]
